### ISSUE TITLE
Could you give an example for your script?

### ISSUE THREAD

**Issue by obaica** [rnels12/getKspaceCOHP#1]
Thank you for sharing the script. 

Could you give an example of how to use your scripts to process the the band-resolved projected crystal orbital Hamilton populations (COHPs)? For example, how to obtain the picture just like TIF reported in the paper (LOBSTER: Local Orbital Projections, Atomic Charges, and Chemical Bonding
Analysis from Projector-Augmented-Wave-Based DFT).

Thank you very much.

**Comment by rnels12** [comment]
An example has been added!
